 dplyr
 install(dplyr)
 install.pakages("dplyr")
 install.pakages("dplyr")
 install.packages("dplyr")
 library(dplyr)
 sessioninfo()
 sessionInfo()
 emptycars
 mtcarsmtcars %>% head()
 dim()mtcars %>% dim()
 mtcars %>% nrow()
 mtcars %>% ncol()
 mtcars %>% names()
 mtcars %>% class()
 mtcars %>% summary()
 iris %>% summary()
 iris %>% glimpse()
 iris2 <- %>% filter(iris, Species == "Setona")
 iris2 <- %>% filter(iris, Species == "Setosa")
 iris2 <- %>% filter(iris, Species == "setosa")
 filter(iris, Species == "setosa")
 iris2 <- filter(iris, Species == "setosa")
 iris2
 iris2 %>% dim()
 iris3 <- iris %>% filter(Sepal.Lenght > 2)
 iris3 %>% dim()
 iris3 <- iris %>% filter(Sepal.Length > 2)
 iris3 %>% dim()
 iris3 <- iris %>% filter(Sepal.Length > 3)
 iris3 %>% dim()
 iris3 <- iris %>% filter(Sepal.Length > 4)
 iris3 %>% dim()
 iris3 %>% dim()
 iris3 %>% dim()
 iris3 %>% dim()
 iris3 %>% dim()
 iris3 %>% dim()
 iris3 %>% dim()
 iris3 <- iris %>% filter(Sepal.Length > 4)
 iris3 %>% dim()iris3 <- iris %>% filter(Sepal.Length > 5.2)iris3 %>% dim()iris3 <- iris %>% filter(Sepal.Length > 5.4)iris3 %>% dim()iris3 <- iris %>% filter(Sepal.Length > 5.6)iris3 %>% dim()history(60)
